### ISSUE TITLE
Specify baseURL for Docusaurus 2 Plugin

### ISSUE THREAD

**Issue by Ekion-1** [akebifiky/remark-simple-plantuml#4]
I've tried to specify a `baseURL` when defining the plugin but it doesn't seem to be making a difference. Am I approaching this the right way?

```javascript
presets: [
    [
      '@docusaurus/preset-classic',
      {
        docs: {

          sidebarPath: require.resolve('./sidebars.js'),
          remarkPlugins: [simplePlantUML( { baseUrl: "<CustomURL>" })]
        },
        blog: {
          showReadingTime: true,
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      },
    ],
  ],
```

**Comment by akebifiky** [comment]
You can specify your custom options like following 👍 

```javascript
presets: [
    [
      '@docusaurus/preset-classic',
      {
        docs: {

          sidebarPath: require.resolve('./sidebars.js'),
          remarkPlugins: [[simplePlantUML, { baseUrl: "CUSTOM_URL" }]]
        },
        blog: {
          showReadingTime: true,
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      },
    ],
  ],

```

In docusaurus, remark plugins with options can be specified as array!
More helps: https://v2.docusaurus.io/docs/markdown-features/#configuring-plugin-options

**Comment by Ekion-1** [comment]
Thanks for the heads up. I've just tried it but all image requests are still coming from `plantuml.com`. Any other suggestions?

![image](https://user-images.githubusercontent.com/6726523/102098187-cc274a00-3e1e-11eb-9127-864bf41bec1c.png)

**Comment by akebifiky** [comment]
Oh, I got same issue😭 
It seems that there is something cached by Docusaurus,
so can you try clearing cache with following command?

```bash
npx docusaurus clear
```

And then, reboot with `docusaurus start` (or your start script)

**Comment by Ekion-1** [comment]
Fantastic, that did it. Thanks!
